export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div>header</div>
      <body>{children}
        <div>footer</div>
      </body>
    </html>
  )
}
